### ISSUE TITLE
What license does this repo have?

### ISSUE THREAD

**Issue by zahrafali** [YtoTech/potyt-fonts-ttf#1]
Hi!
I wanted to know what kind of license your repo has and whether I can use it for my project for commercial purposes.

Thanks

**Comment by MonsieurV** [comment]
Hi @zahrafali,

These fonts are mostly proprietary fonts: you must for each of them that your usage is compliant with the font editor license.

You can look for font licenses on:
* Apple fonts: https://developer.apple.com/fonts/
* Microsoft fonts: https://docs.microsoft.com/en-us/typography/font-list/

The repo is provided "as is": it does not endorse the usage of the fonts outside their license conditions; and it is not a recognized distributor not owner for these fonts.

**Comment by MonsieurV** [comment]
Added a note in the README ;)
